name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Playwright dependencies
        run: npx playwright install --with-deps

      - name: Test e2e
        run: npm run test:e2e

      - name: Deploy to Render
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}